[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
sol_usd_oracle = "qgMxYoiKq6imJNLcnJCGsEZFNqCk7jkpEPPrVigwE55"
token_minter = "HZ8ztnxaaLYgGb33c4t4mp5pxHELn4kN8xbxfG67sdCG"

[programs.localnet]
sol_usd_oracle = "qgMxYoiKq6imJNLcnJCGsEZFNqCk7jkpEPPrVigwE55"
token_minter = "HZ8ztnxaaLYgGb33c4t4mp5pxHELn4kN8xbxfG67sdCG"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
litesvm = "yarn run mocha -t 1000000 \"tests/**/*.ts\""
test = "yarn run mocha -t 1000000 \"tests/**/*.ts\""

[hooks]
